[mypy]
# 🟢 Core configurations
ignore_missing_imports = True
follow_imports = skip
exclude = (?x)(
    ^usr/

    | ^anaconda3/
    | \.venv/
  )

# 🟢 Explicitly isolate specific messy third-party dependencies
[mypy-google.*]
ignore_missing_imports = True

[mypy-langchain.*]
ignore_missing_imports = True
